IDIR = ../include
LDIR = ../lib
ODIR = ../objects

CC=gcc
CFLAGS=-pthread -I$(IDIR)

_DEPS = RPio.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))
_OBJ = RPio.o RPio_midiuart.o matrixkeyboard.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

matrixkeyboard:  $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~


